services:
  - type: web
    name: trend-reports-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --log-level info

    # Environment variables
    envVars:
      - key: API_KEY
        generateValue: true  # Render will auto-generate secure key

      - key: ENVIRONMENT
        value: production

      - key: CHROMA_DB_PATH
        value: /app/chroma_data

      - key: REPORTS_FOLDER
        value: /app/2025 Trend Reports

      - key: CHUNK_SIZE
        value: "800"

      - key: OVERLAP
        value: "150"

      - key: RATE_LIMIT
        value: 20/minute  # Increased for production

      - key: ALLOWED_ORIGINS
        value: https://chat.openai.com,https://chatgpt.com

    # Persistent disk for ChromaDB
    disk:
      name: chroma-data
      mountPath: /app/chroma_data
      sizeGB: 10

    # Health check configuration
    healthCheckPath: /health

    # Auto-deploy on git push
    autoDeploy: true
